name: Workflow-Pipeline

on:
  push:
    branches:
      - main
      - development
    tags:
      - "*"
  pull_request:
    branches:
      - main
      - development

jobs:
  Unit-Testing:
    name: Unit Testing🛠
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.30
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "password"

      localstack:
        image: localstack/localstack
        ports:
          - "4566:4566"
        env:
          SERVICES: "sns"
          DEFAULT_REGION: "eu-central-1"
          AWS_ACCESS_KEY_ID: "dummy1"
          AWS_SECRET_ACCESS_KEY: "dummy1"

      redis:
        image: redis:7.0.5
        ports:
          - "6379:6379"
        options: "--entrypoint redis-server"

      zipkin:
        image: openzipkin/zipkin:2
        ports:
          - "9411:9411"

      elasticsearch:
        image: elasticsearch:6.8.6
        ports:
          - 2012:9200
          - 2013:9300
          - 9200:9200
        env:
          discovery type: "single-node"

      kafka:
        image: krisgeus/docker-kafka
        ports:
          - 2008:2008
          - 2009:2009
        env:
          ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:2008,INTERNAL://localhost:2009'
          LISTENERS: 'PLAINTEXT://0.0.0.0:2008,INTERNAL://0.0.0.0:2009'
          SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT'
          INTER_BROKER: 'INTERNAL'
          KAFKA_CREATE_TOPICS: 'test-topic'
          KAFKA_HOSTS: 'localhost:2008,localhost:2009'
          KAFKA_TOPIC: 'test-topic'

      mongo:
        image: mongo:6.0.2
        ports:
          - "27017:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin123

      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - "1433:1433"
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: reallyStrongPwd123

      dynamodb:
        image: amazon/dynamodb-local:1.22.0
        ports:
          - "2021:8000"

      postgres:
        image: postgres:15.1
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: test

      cassandra:
        image: cassandra:4.1
        ports:
          - 9041:9042
        options: --health-cmd "cqlsh --debug"

    steps:
      - name: Checkout code into go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up  Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: Go

      - name: Set UP AWS-CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

      - name: Run initializing command for AWS-CLI
        run: |
          unzip awscliv2.zip
          sudo ./aws/install
          echo "AWS CLI installation completed."

      - name: Run docker for AWS-CLI
        run: |
          docker-compose -f examples/using-awssns/Docker-Compose.yml up -d

      - name: Configure AWS CLI profile
        run: |
          aws configure --profile test-profile
          aws configure set aws_access_key_id dummy1 --profile test-profile
          aws configure set aws_secret_access_key dummy1 --profile test-profile
          aws configure set region eu-central-1 --profile test-profile

      - name: Create SNS topic
        run: |
          topic_arn=$(aws --endpoint-url=http://localhost:4566 sns create-topic --name order-creation-events --region eu-central-1 --profile test-profile | grep -o 'arn[^"]*')
          echo "APP_VERSION=v0" > examples/using-awssns/configs/.local.env
          echo "APP_NAME=aws-sns-example" >> examples/using-awssns/configs/.local.env
          echo "HTTP_PORT=8080" >> examples/using-awssns/configs/.local.env
          echo "SNS_ACCESS_KEY=dummy1" >> examples/using-awssns/configs/.local.env
          echo "SNS_SECRET_ACCESS_KEY=dummy1" >> examples/using-awssns/configs/.local.env
          echo "SNS_REGION=eu-central-1" >> examples/using-awssns/configs/.local.env
          echo "SNS_PROTOCOL=http" >> examples/using-awssns/configs/.local.env
          echo "SNS_ENDPOINT=http://localhost:4566/" >> examples/using-awssns/configs/.local.env
          echo "SNS_TOPIC_ARN=$topic_arn" >> examples/using-awssns/configs/.local.env
          echo "NOTIFIER_BACKEND=SNS" >> examples/using-awssns/configs/.local.env

      - name: Load Schema of Cassandra
        run: |
          docker exec -i ${{ job.services.cassandra.id }} cqlsh --debug  < .github/setups/keyspace.cql

      - name: Yugabyte setup
        uses: yugabyte/yugabyte-db-action@master
        with:
          yb_image_tag: 2.14.5.0-b18
          yb_master_ui_port: 7000
          yb_tserver_ui_port: 6000
          ysql_port: 5433
          ycql_port: 9042

      - name: Set up MySQL
        run: |
          docker exec -i ${{ job.services.mysql.id }} mysql -uroot -ppassword -e 'CREATE DATABASE test;'

      - name: Set up SSL Enabled MySQL
        run: |
          docker run --name gofr-ssl-mysql -e MYSQL_ROOT_PASSWORD=password -p 2001:3306 -d mysql:8.0.31
          docker cp ${{ github.workspace }}/.github/setups/certFiles gofr-ssl-mysql:/usr/certFiles
          docker cp ${{ github.workspace }}/.github/setups/my.cnf gofr-ssl-mysql:/etc/my.cnf
          docker exec -i gofr-ssl-mysql chown -Rf mysql. /usr/certFiles
          docker restart gofr-ssl-mysql

      - name: Load Schema of YCQL
        run: |
          temp=$(sudo docker ps | grep yugabyte | awk '{print $1}');
          docker exec -i $temp /home/yugabyte/bin/ycqlsh < .github/setups/keyspace.ycql;

      - name: Get dependencies
        run: |
          go mod download

      - name: Load Schema of Solr
        run: |
          docker run -d --name solr -p 8983:8983 solr:8 -DzkRun;
          sleep 10s;
          docker exec -i solr sh < .github/setups/solrSchema.sh;

      - name: Setup SFTP Server
        run: |
          mkdir $HOME/sftpData
          chmod -R 777 $HOME/sftpData
          docker run --name gofr-sftp -v $HOME/upload:/home/myuser -p 2222:22 -d atmoz/sftp myuser:mypass:1001

      - name: Setup FTP Server
        run: |
          mkdir $HOME/ftpData
          chmod -R 777 $HOME/ftpData
          docker run -d --name gofr-ftp -v $HOME/ftpData:/home/vsftpd -p 20:20 -p 21:21 -p 21100-21110:21100-21110 -e FTP_USER=myuser \
          -e FTP_PASS=mypass -e PASV_ADDRESS=127.0.0.1 -e PASV_MIN_PORT=21100 -e PASV_MAX_PORT=21110 fauria/vsftpd

      - name: Setup Google PubSub
        run: |
          docker pull gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
          docker run --name=gcloud-emulator -d -p 8086:8086 \
          gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators gcloud beta emulators pubsub start --project=test123 \
          --host-port=0.0.0.0:8086

      - name: Test
        run: |
          export GOFR_ENV=test
          cd examples/using-awssns
          go test ./... -v -short -coverprofile profile.cov -coverpkg=./...          
          go tool cover -func profile.cov

      - name: Upload Test Coverage to Code Climate
        if: ${{ always() }}
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          debug: true
          coverageLocations: profile.cov:gocov
          prefix: gofr.dev

  code_quality:
    name: Code Quality🎖️
    runs-on: ubuntu-latest
    container: "golangci/golangci-lint:v1.52.2"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: GolangCI-Lint
        run: |
          golangci-lint run --timeout 9m0s
